### PR TITLE
Add support for setting a block of yaml

### PR DESCRIPTION
**Pull request by mgates**
Co-authored-by: Jonathan Radon <jon@radonfamily.com>

Hey there - this is super not done yet - we need to add tests and error handling, and we don't write a lot of python, so there's probably plenty to improve, but we thought we'd try to start the conversation early.

This adds the ability to add a block of yaml (or, I suppose json) to an existing file instead of a single value.

Any thoughts as we continue with it?

### CODE REVIEW

**Comment by wwkimball** [comment]
If I might offer some initial thoughts:

1. Thank you for taking an interest in this project!  I love contributions because they help add bug-fixes and features where I just don't personally have enough free time to lend attention.  So, by all means, have at it!
2. This library sits on top of [ruamel.yaml](https://bitbucket.org/ruamel/yaml/src/default/), which parses YAML/Compatible data into a DOM.  So, if you're thinking of dropping a chunk of raw YAML/JSON into a source file like a simple String-based copy-paste, I suspect you'll hit a pretty big speed-bump.  It's not trivial to add a raw chunk of YAML/JSON into a parsed DOM.
3. I suspect that what you really need is to merge two DOMs together.  To that end, you should consider creating a new command, yaml-merge, rather than attempting to add merging capability to yaml-set.  In fact, I'd love to have such a command as part of this project!
4. This project consists of two major components:  a reusable library (everything under ./yamlpath/* except the commands directory) and some example implementations of the library as commands.  When adding new capabilities, be sure to add them to the library, first.  Then, expose the new capabilities through the commands or even add new commands.

**Comment by JonMR** [comment]
Hi @wwkimball 

We like the project a lot and have quite a few use cases for it. We're familiar with ruamel.yaml at a surface level. We initially started down the path of writing our own tool before we discovered your project. 

To your point about raw YAML/JSON, I believe this change does parse the YAML the user provides. The code calls `get_yaml_data`, which eventually calls `YAML.load` on the new YAML provided by the user. That returns a `CommentedMap` from what I see. It's possible we misunderstood the API though.

We could break this out into a separate command if you feel strongly about it. It felt to us like `yaml-set` and a new `yaml-merge` would have a lot of overlapping options and functionality. So we went with the least invasive approach.

**Comment by wwkimball** [comment]
Some brain-storming fodder (I'm not shutting anything down and I hope this doesn't come across as overly critical):

I see special cases being added for incompatible arguments as well as unit tests being created for special combinations of parameters.  If we find ourselves needing special cases for an otherwise simple idea, we might be overloading the purpose of the original code; in this case, `yaml-set`.  The purpose of `yaml-set` is to easily set the value of a simple value at the end of a YAML Path.  Injecting YAML/Compatible data exceeds that purpose.  A new command seems a better fit based on overloading the original purpose of the command.

I see conflict between the options `yaml-set` offers and what you need for this idea.  That makes me further feel like you need a new command.  If not `yaml-merge` (arguably more complex than what you're after), what about `yaml-inject`?  Don't worry about overlap between the commands.  They're just variants of implementations of the shared library, anyway.  To wit, overlap in their arguments actually makes the whole family of tools simpler to use.

There are more special cases that come into play which a unique tool may be better suited to handle:
* What if the data being injected brings anchors?  Are you checking for duplicate anchor names?  Are you offering to amend the anchor names so the result doesn't crash the DOM (say, by appending some dynamic/random prefix/suffix)?
* What if the data being injected brings aliases?  Are you checking that an anchor has been defined to supply the (missing) data?  Are they in/compatible scalar or map aliases?

**Comment by JonMR** [comment]
Thanks @wwkimball for the response.

It sounds like you think a separate command is the way to go, so we'll start down that path. There are a few notes, though, if you think it makes a difference:

1. Strictly speaking, `yaml-insert` would be a superset of `yaml-set`. Anything `yaml-set` is capable of setting is also technically yaml. So `yaml-insert` would be capable of all functionality provided by `yaml-set`.
2. `yaml-insert` would also be capable of replacing yaml subtree at a particular node. Which sounds a bit like `set` rather than `insert`.
3. We could resolve the option conflicts. First, we could remove the `--yaml` option and use `--format yaml`. We debated which was better initially. Second, since `--random` technically produces yaml, we could remove that option exclusion as well.

We're also looking into anchors and aliases, right now it looks like it will only be straightforward to add yaml that is valid on its own (that it, it contains the anchors for its own aliases). We're still looking, but if you think of any other special cases, let us know.

Thanks for being so responsive and working through this with us.

**Comment by wwkimball** [comment]
I'm not dead-set against adding this capability to `yaml-set`.  I only feel like it's a murky muddling of the original purpose of `yaml-set` (to set a simple, scalar value).  That said, I agree that at a high conceptual level, `yaml-set` sounds like the right place to also permit setting complex data.  It was the conflicting parameters that concerned me the most; if the two separate concepts couldn't co-exist in one tool, then we necessarily needed a new tool.

If you can make your addition "play nice" with the existing parameters of `yaml-set`, please do so.  Note that if you really end up with conflicting parameters, please try to use `parser.add_mutually_exclusive_group()` -- if possible -- to let the command-line parser deal with the conflict -- and make the exclusivity apparent in the self-documentation -- rather than add custom code to handle it.

This is more important than argument conflicts:  we have to permit users to inject anchors and aliases, and expect them to work.  If you're tracking this as a story, please consider these requirements:
1. Users want to add YAML with either or both anchors and aliases.
2. Users want existing anchors to feed my same-named aliases.
3. Users want to overwrite existing anchors and have such changes correctly impact existing aliases of it.
4. Users may accidentally inject anchors later in YAML that conflicts with a same-named anchor; the code must detect this and **reject** the addition.  We must **expressly not** provide any means of automatically changing anchor names because when aliases exist to the anchor name, there is no way to know whether the user *mistakenly* used the same anchor name and meant for those aliases to point to *their* anchor or the *pre-existing* anchor.  Even if there are no aliases in the YAML-to-Inject, block conflicting anchor names.

**Comment by wwkimball** [comment]
Follow-Up:  Is your team still interested in this capability?

**Comment by JonMR** [comment]
Hey William. We are still interested, but making the functionality work with anchors proved fairly difficult. Part of our struggle might have been our unfamiliarity with the code. We spent a few days trying to get that working and ultimately had to switch our focus to another project.

So in short, we might come back to it, but it likely won’t be for a while.

**Comment by wwkimball** [comment]
You are absolutely right; anchors and aliases consumed more of my own time on this project than any other capability.  I'll temporarily close this PR, for now.  Please feel free to reopen it whenever your interest waxes back this way!

**Comment by wwkimball** [comment]
@mgates  and @JonMR please know that I finally took up this challenge and have created a new `yaml-merge` tool which fully addresses this use-case.

More detail is available at https://github.com/wwkimball/yamlpath/issues/56#issuecomment-701148384 and I've exhaustively updated the Wiki with details of the new tool at https://github.com/wwkimball/yamlpath/wiki/yaml-merge.

I hope you find this new tool meets your expectations!

**Comment by mgates** [comment]
This is amazing - thanks for the ping.

**Pull request closed without merging**
